name: CI
on:
  pull_request:
  push:
    branches: main

jobs:
  zig-tests:
    runs-on: ubuntu-latest
    name: Zig Tests
    defaults:
      run:
        working-directory: zig

    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Run Tests
        run: zig test src/lexer.zig

  elixir-tests:
    runs-on: ubuntu-latest
    name: Elixir Tests
    defaults:
      run:
        working-directory: elixir

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.0"
          elixir-version: "1.13.4"

      - name: Run Tests
        run: mix test
